global:
  scrape_interval: 1m
  scrape_timeout: 30s

scrape_configs:
  - job_name: 'server-exp'
    static_configs:
      - targets: ['Your_exporter_server_IP:9100']

############ BLACKBOX LOC#1 START ############

  - job_name: 'blackbox-http-site1'
    metrics_path: /probe
    params:
      module: [http_2xx]
    file_sd_configs:
      - files:
          - '/etc/prometheus/http/*.json'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: [YOUR_BLACKBOX_SERVER1_IP]:9115

  - job_name: 'blackbox-icmp-site1'
    metrics_path: /probe
    params:
      module: [icmp]
    file_sd_configs:
      - files:
          - '/etc/prometheus/icmp/*.json'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: [YOUR_BLACKBOX_SERVER1_IP]:9115

############ BLACKBOX LOC#1 END ############

############ BLACKBOX LOC#2 START ############

  - job_name: 'blackbox-http-site2'
    metrics_path: /probe
    params:
      module: [http_2xx]
    file_sd_configs:
      - files:
          - '/etc/prometheus/http/*.json'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: [YOUR_BLACKBOX_SERVER2_IP]:9115

  - job_name: 'blackbox-icmp-site2'
    metrics_path: /probe
    params:
      module: [icmp]
    file_sd_configs:
      - files:
          - '/etc/prometheus/icmp/*.json'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: [YOUR_BLACKBOX_SERVER2_IP]:9115

############ BLACKBOX LOC#2 END ############

  - job_name: 'mysql'
    static_configs:
      - targets: ['YOUR_MYSQL_SERVER1_IP:9104']
        labels:
          server: database_server1
      - targets: ['YOUR_MYSQL_SERVER2_IP:9104']
        labels:
          server: database_server2
          
  - job_name: 'mysql-rep'
    metrics_path: /metrics
    static_configs:
      - targets: ['replica-server:9105']
        labels:
          server: replica-server

  - job_name: 'supervisor'
    metrics_path: /metrics
    static_configs:
      - targets: ['YOUR_SUPERVISOR_SERVER_IP:9200']

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: ['alertmanager:9093']

rule_files:
  - '/etc/prometheus/rules/*.rules'
