global:
  scrape_interval: 1m

scrape_configs:
  - job_name: 'main-exp'
    static_configs:
      - targets: ['1.2.3.4:9100']

  - job_name: 'mysql'
    static_configs:
      - targets: ['1.2.3.4:9104']
        labels:
          server: mainserver-database
      - targets: ['replica-server:9104']
        labels:
          server: replica-server

  - job_name: 'supervisor'
    metrics_path: /metrics
    static_configs:
      - targets: ['1.2.3.4:9200']
      
  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - https://domain.com
        - https://domain2.com
        - https://gitlab.domain.com:8093
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 1.2.3.4:9115

alerting:
  alertmanagers:
    - scheme: http
      static_configs:
        - targets: [ 'monitoring.domain.com:9093' ]

rule_files:
  - alert-rules.yml
