groups:
- name: alert.rules
  rules:

  - alert: HostOutOfMemory
    expr: node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100 < 25
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Host out of memory (instance {{ $labels.instance }})"
      description: "Node memory is filling up (< 25% left)\n  VALUE = {{ $value }}\n  LABELS: {{ $labels }}"

  # Alert for any instance that is unreachable for >1 minute.
  - alert: InstanceDown
    expr: up == 0
    for: 1m
    labels:
      severity: page
    annotations:
      summary: "Instance {{ $labels.instance }} down"
      description: "{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute."

  # Low disk space alert
  - alert: LowDiskSpace
    expr: node_filesystem_avail_bytes{device="/dev/mapper/ubuntu--vg-ubuntu--lv", fstype="ext4", instance="1.2.3.4:9100", job="main-exp", mountpoint="/"} /1024/1024/1024 < 50
    for: 30m
    labels:
      severity: critical
    annotations:
      summary: Low disk space on host {{ $labels.instance }}
      description: The free disk space on host {{ $labels.instance }} has dropped below 50G
